<?php

use Illuminate\Database\Seeder;

class RecomendationsTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        

        \DB::table('recomendations')->delete();
        
        \DB::table('recomendations')->insert(array (
            0 => 
            array (
                'id' => 1,
                'typeofrecomendations_id' => 1,
                'country_id' => 1,
                'name' => 'Implicar mas activamente a la sociedad civil en la elaboración de políticas,estrategias y planes de acción nacionales de derechos humanos.	',
                'details' => '',
                'total' => 0.0,
                'created_at' => '2016-12-14 20:56:41',
                'updated_at' => '2016-12-14 21:59:55',
            ),
            1 => 
            array (
                'id' => 2,
                'typeofrecomendations_id' => 1,
                'country_id' => 1,
                'name' => 'Intensificar los esfuerzos destinados a reformar el sector de la justicia y la seguridad con miras a combatir la corrupcion y reforzar la independencia del poder judicial,entre otras cosas fomentando una supervision y un control disciplinario efectivo de',
                'details' => '',
                'total' => 0.0,
                'created_at' => '2016-12-14 21:25:53',
                'updated_at' => '2016-12-14 22:07:49',
            ),
            2 => 
            array (
                'id' => 8,
                'typeofrecomendations_id' => 1,
                'country_id' => 1,
                'name' => 'Adoptar medidas adicionales para garantizar la igualdad de acceso a de las mujeres a servicios de salud adecuados, en especial a servicios de salud sexual y reproductiva,y ratificar el OP-CEDAW',
                'details' => '',
                'total' => 0.0,
                'created_at' => '2016-12-14 23:21:06',
                'updated_at' => '2016-12-14 23:21:06',
            ),
            3 => 
            array (
                'id' => 9,
                'typeofrecomendations_id' => 1,
                'country_id' => 2,
                'name' => 'Intensificar las políticas socioeconomicas para permitir la participación activa de las personas afrodescendientes en la esfera económica, social y política.',
                'details' => '',
                'total' => 0.0,
                'created_at' => '2016-12-14 23:23:50',
                'updated_at' => '2016-12-14 23:23:50',
            ),
            4 => 
            array (
                'id' => 10,
                'typeofrecomendations_id' => 1,
                'country_id' => 2,
                'name' => 'Reforzar el sistema de proteccion de las personas en situacion de riesgo,sobre todo las mujeres y los niños',
                'details' => '',
                'total' => 0.0,
                'created_at' => '2016-12-14 23:24:16',
                'updated_at' => '2016-12-14 23:24:16',
            ),
            5 => 
            array (
                'id' => 11,
                'typeofrecomendations_id' => 1,
                'country_id' => 3,
                'name' => 'Seguir aplicando la política Publica y plan nacional de acción en derechos humanos 2013-2022',
                'details' => '',
                'total' => 0.0,
                'created_at' => '2016-12-14 23:24:42',
                'updated_at' => '2016-12-14 23:24:42',
            ),
            6 => 
            array (
                'id' => 12,
                'typeofrecomendations_id' => 1,
                'country_id' => 3,
                'name' => 'Continuar con su política de reducción de la violencia contra los niños y jóvenes',
                'details' => '',
                'total' => 0.0,
                'created_at' => '2016-12-14 23:25:08',
                'updated_at' => '2016-12-14 23:25:08',
            ),
            7 => 
            array (
                'id' => 13,
                'typeofrecomendations_id' => 1,
                'country_id' => 4,
                'name' => 'Fortalecer el funcionamiento de la comision nacional contra la discriminacion racial,el racismo,la xenofobia y las formas conexas de intolerancia, a fin de favorecer los programas de dialogo interestructural,tolerancoa y sensibilizacion',
                'details' => '',
                'total' => 0.0,
                'created_at' => '2016-12-14 23:25:59',
                'updated_at' => '2016-12-14 23:25:59',
            ),
            8 => 
            array (
                'id' => 14,
                'typeofrecomendations_id' => 1,
                'country_id' => 4,
                'name' => 'Continuar profundizando las medidas judiciales y administrativas iniciadas para hacer efectiva la investigacion y sancion de los autores de actos de violencia,en particular aquellos dirigidos contra los defensores de los derechos humanos',
                'details' => '',
                'total' => 0.0,
                'created_at' => '2016-12-14 23:26:27',
                'updated_at' => '2016-12-14 23:26:27',
            ),
            9 => 
            array (
                'id' => 15,
                'typeofrecomendations_id' => 1,
                'country_id' => 5,
                'name' => 'Garantizar la libertad de expresion y adoptar las medidas para acabar con las amenazas y los ataques contra periodistas y defensores de los derechos humanos incluidas las personas lesbianas gais,bisexuales,transgenero e intersexuales',
                'details' => '',
                'total' => 0.0,
                'created_at' => '2016-12-14 23:26:57',
                'updated_at' => '2016-12-14 23:26:57',
            ),
            10 => 
            array (
                'id' => 16,
                'typeofrecomendations_id' => 1,
                'country_id' => 5,
                'name' => 'Seguir reforzando la respuesta del sistema de justicia penal a la delicuencia violenta contra mujeres y niñas y en particular las medidas de apoyo',
                'details' => '',
                'total' => 0.0,
                'created_at' => '2016-12-14 23:27:35',
                'updated_at' => '2016-12-14 23:27:35',
            ),
            11 => 
            array (
                'id' => 17,
                'typeofrecomendations_id' => 1,
                'country_id' => 1,
                'name' => 'Acabar, en la ley y en la practica con la discriminación de que son victimas los pueblos indígenas y afrohondureños ,y reforzar la protección de las personas lesbianas, gais, bisexuales, transgenero e intersexuales.',
                'details' => '',
                'total' => 0.0,
                'created_at' => '2016-12-14 23:29:15',
                'updated_at' => '2016-12-14 23:29:15',
            ),
            12 => 
            array (
                'id' => 18,
                'typeofrecomendations_id' => 1,
                'country_id' => 6,
                'name' => 'Adoptar medidas eficaces para adecuar las condiciones de detención a las normas internacionales , en particular reduciendo el hacinamiento y la violencia entre los reclusos .',
                'details' => '',
                'total' => 0.0,
                'created_at' => '2016-12-14 23:30:43',
                'updated_at' => '2016-12-14 23:30:43',
            ),
            13 => 
            array (
                'id' => 19,
                'typeofrecomendations_id' => 1,
                'country_id' => 6,
                'name' => 'Investigar de manera rápida e imparcial las denuncias de represalias contra periodista y defensores de derechos humanos, y velar que los responsables rindan cuentas de sus actos.',
                'details' => '',
                'total' => 0.0,
                'created_at' => '2016-12-14 23:31:05',
                'updated_at' => '2016-12-14 23:31:05',
            ),
            14 => 
            array (
                'id' => 20,
                'typeofrecomendations_id' => 1,
                'country_id' => 6,
            'name' => 'Ratificar protocolo facultativo de la convención sobre la eliminación de todas las formas de discriminación contra la mujer (PO-CEDAW)',
                'details' => '',
                'total' => 0.0,
                'created_at' => '2016-12-14 23:31:36',
                'updated_at' => '2016-12-14 23:31:36',
            ),
            15 => 
            array (
                'id' => 21,
                'typeofrecomendations_id' => 1,
                'country_id' => 7,
                'name' => 'Garantizar la protección y el acceso a la justicia de las mujeres victimas de la violencia.',
                'details' => '',
                'total' => 0.0,
                'created_at' => '2016-12-14 23:32:00',
                'updated_at' => '2016-12-14 23:32:00',
            ),
            16 => 
            array (
                'id' => 22,
                'typeofrecomendations_id' => 1,
                'country_id' => 7,
                'name' => 'Velar por que todas denuncias de violaciones de los derechos humanos y otros abusos cometidos por la policía, las fuerzas armadas o miembros de las empresas privadas de seguridad se investiguen de manera rápida,independiente y exhaustiva, y porque los responsables de esas violaciones comparezcan ante la justicia y las victimas tengan derecho a reparaciones.',
                'details' => '',
                'total' => 0.0,
                'created_at' => '2016-12-14 23:32:48',
                'updated_at' => '2016-12-14 23:42:29',
            ),
            17 => 
            array (
                'id' => 23,
                'typeofrecomendations_id' => 1,
                'country_id' => 7,
                'name' => 'Aprobar y aplicar la ley de protección de defensores de derechos humanos,periodistas,comunicadores sociales y operadores de justicia y asignar suficientes recursos humanos y financieros para establecer un mecanismo de estado eficaz que proteja a las personas en situación de riesgo.',
                'details' => '',
                'total' => 0.0,
                'created_at' => '2016-12-14 23:33:09',
                'updated_at' => '2016-12-14 23:42:05',
            ),
            18 => 
            array (
                'id' => 24,
                'typeofrecomendations_id' => 1,
                'country_id' => 8,
                'name' => 'Reforzar las instituciones nacionales encargadas de promover y proteger los derechos humanos, con miras a fomentar el acceso a la justicia,en particular de los grupos mas vulnerables,como las mujeres,los ancianos, los niños,los pueblos indígenas, las personas con discapacidad,las personas afro descendientes y la comunidad de personas lebianas, gais, transgenero e intersexuales.',
                'details' => '',
                'total' => 0.0,
                'created_at' => '2016-12-14 23:33:41',
                'updated_at' => '2016-12-14 23:41:38',
            ),
            19 => 
            array (
                'id' => 25,
                'typeofrecomendations_id' => 1,
                'country_id' => 8,
                'name' => 'Garantizar la aplicación efectiva del proyecto de ley de protección de defensores de derechos humanos, periodistas, comunicadores sociales y operadores de justicia, entre otras cosas mediante una financiación adecuada.',
                'details' => '',
                'total' => 0.0,
                'created_at' => '2016-12-14 23:43:19',
                'updated_at' => '2016-12-14 23:43:19',
            ),
            20 => 
            array (
                'id' => 26,
                'typeofrecomendations_id' => 1,
                'country_id' => 9,
                'name' => ' Defender los derechos del niño asegurando que la dirección de la niñez, adolescencia y familia cuente con un marco legislativo adecuado y con recursos financieros para poder desempeñar su mandato , aplicando programas y políticas de protección de los niños , los adolescentes y los niños migrantes que vuelven al país.',
                'details' => '',
                'total' => 0.0,
                'created_at' => '2016-12-15 00:23:47',
                'updated_at' => '2016-12-15 00:24:53',
            ),
            21 => 
            array (
                'id' => 27,
                'typeofrecomendations_id' => 1,
                'country_id' => 9,
                'name' => ' Reforzar el poder judicial y garantizar su independencia e imparcialidad,aplicando el proceso constitucional para la elección de los jueces de la corte suprema, adoptando medidas de salvaguardia para impedir los nombramientos y las destituciones irregulares adoptando medidas de lucha contra la corrupción.',
                'details' => '',
                'total' => 0.0,
                'created_at' => '2016-12-15 00:25:24',
                'updated_at' => '2016-12-15 00:25:24',
            ),
            22 => 
            array (
                'id' => 28,
                'typeofrecomendations_id' => 1,
                'country_id' => 9,
                'name' => 'Aumentar la cantidad de agentes del orden,jueces y fiscales que reciben capacitación especifica en materia de derechos humanos y grupos minoritarios.',
                'details' => '',
                'total' => 0.0,
                'created_at' => '2016-12-15 00:26:16',
                'updated_at' => '2016-12-15 00:26:16',
            ),
            23 => 
            array (
                'id' => 29,
                'typeofrecomendations_id' => 1,
                'country_id' => 10,
                'name' => ' Reforzar las acciones tendientes a eliminar aquellos patrones culturales que discriminan a la mujer, promoviendo , un acceso adecuado a la protección judicial para evitar que casos de violencia que afectan su vida,salud e integridad queden en la impunidad.',
                'details' => '',
                'total' => 0.0,
                'created_at' => '2016-12-15 00:27:24',
                'updated_at' => '2016-12-15 00:27:24',
            ),
            24 => 
            array (
                'id' => 30,
                'typeofrecomendations_id' => 1,
                'country_id' => 10,
                'name' => 'Reforzar las acciones tendientes a eliminar aquellos patrones culturales que discriminan a la mujer, promoviendo , un acceso adecuado a la protección judicial para evitar que casos de violencia que afectan su vida,salud e integridad queden en la impunidad.',
                'details' => '',
                'total' => 0.0,
                'created_at' => '2016-12-15 00:28:20',
                'updated_at' => '2016-12-15 00:28:20',
            ),
            25 => 
            array (
                'id' => 31,
                'typeofrecomendations_id' => 1,
                'country_id' => 10,
                'name' => 'Establecer mecanismos efectivos que permitan garantizar la seguridad de los defensores de derechos humanos,los jueces,los fiscales, y los periodistas,y evitar que los actos de violencia ,con resultado de muerte,en muchos casos, intimidación y atentados que sufren esas personas se mantengan en impunidad.',
                'details' => '',
                'total' => 0.0,
                'created_at' => '2016-12-15 00:29:02',
                'updated_at' => '2016-12-15 00:29:02',
            ),
            26 => 
            array (
                'id' => 32,
                'typeofrecomendations_id' => 1,
                'country_id' => 10,
            'name' => ' Considerar ratificar el OP-CEDAW (Uruguay); avanzar en la ratificación del OP-CEDAW',
                'details' => '',
                'total' => 0.0,
                'created_at' => '2016-12-15 00:29:25',
                'updated_at' => '2016-12-15 00:29:25',
            ),
            27 => 
            array (
                'id' => 33,
                'typeofrecomendations_id' => 1,
                'country_id' => 11,
                'name' => 'Seguir centrándose en desarrollar la economía, aumentar el empleo,reforzar la erradicación de la pobreza y mejorar el nivel de vida de la población.',
                'details' => '',
                'total' => 0.0,
                'created_at' => '2016-12-15 00:30:29',
                'updated_at' => '2016-12-15 00:30:29',
            ),
            28 => 
            array (
                'id' => 34,
                'typeofrecomendations_id' => 1,
                'country_id' => 12,
                'name' => 'Continuar con la aplicación efectiva de las medidas para la lucha contra la discriminacion y la violencia por razones de orientacion sexual e identidad de genero,en particular a traves de la implementacion de enfoques diferenciales que garanticen el goce de los derechos de las personas lesbianas,gais,bisexuales,transgenero e intersexuales',
                'details' => '',
                'total' => 0.0,
                'created_at' => '2016-12-15 00:30:53',
                'updated_at' => '2016-12-15 00:30:53',
            ),
            29 => 
            array (
                'id' => 35,
                'typeofrecomendations_id' => 1,
                'country_id' => 12,
                'name' => 'Tomar medidas para el empoderamiento de los jóvenes, en particular a través de la educación, para evitar que se engrosen las bandas criminales y traficantes; y asegurar su rehabilatación y reinserción social.',
                'details' => '',
                'total' => 0.0,
                'created_at' => '2016-12-15 00:31:39',
                'updated_at' => '2016-12-15 00:31:39',
            ),
            30 => 
            array (
                'id' => 36,
                'typeofrecomendations_id' => 1,
                'country_id' => 12,
                'name' => 'Seguir dando prioridad a los esfuerzos encaminados al reconocimiento y la proteccion de los periodistas y los defensores de derechos humanos.',
                'details' => '',
                'total' => 0.0,
                'created_at' => '2016-12-15 00:32:14',
                'updated_at' => '2016-12-15 00:32:14',
            ),
            31 => 
            array (
                'id' => 37,
                'typeofrecomendations_id' => 1,
                'country_id' => 13,
                'name' => 'Fortalecer el aparato de seguridad A través de una policía civil para luchar contra la impunidad,especialmente en los casos de delitos contra y de femicidios, sin involucrar al aparato militar.',
                'details' => '',
                'total' => 0.0,
                'created_at' => '2016-12-15 00:33:37',
                'updated_at' => '2016-12-15 00:33:37',
            ),
            32 => 
            array (
                'id' => 38,
                'typeofrecomendations_id' => 1,
                'country_id' => 13,
            'name' => 'Ratificar protocolo facultativo de la convención sobre la eliminación de todas las formas de discriminación contra la mujer (PO-CEDAW)',
                'details' => '',
                'total' => 0.0,
                'created_at' => '2016-12-15 00:34:17',
                'updated_at' => '2016-12-15 00:34:17',
            ),
            33 => 
            array (
                'id' => 39,
                'typeofrecomendations_id' => 1,
                'country_id' => 13,
            'name' => 'Ratificar el protocolo facultativo del pacto internacional de derechos Económicos, Sociales y Culturales (OP-ICESCR).',
                'details' => '',
                'total' => 0.0,
                'created_at' => '2016-12-15 00:35:15',
                'updated_at' => '2016-12-15 00:35:15',
            ),
            34 => 
            array (
                'id' => 40,
                'typeofrecomendations_id' => 1,
                'country_id' => 14,
                'name' => 'Continuar la aplicación de acciones concretas para la puesta en vigor de la Ley Fundamental de Educación.',
                'details' => '',
                'total' => 0.0,
                'created_at' => '2016-12-15 00:39:41',
                'updated_at' => '2016-12-15 00:39:41',
            ),
            35 => 
            array (
                'id' => 41,
                'typeofrecomendations_id' => 1,
                'country_id' => 14,
                'name' => 'Seguir implementado medidas para abordar integralmente el fenómeno de los niños migrantes no acompañados.',
                'details' => '',
                'total' => 0.0,
                'created_at' => '2016-12-15 00:41:43',
                'updated_at' => '2016-12-15 00:41:43',
            ),
            36 => 
            array (
                'id' => 42,
                'typeofrecomendations_id' => 1,
                'country_id' => 15,
                'name' => 'Aplicar las recomendaciones que figuran en el informe de 2013 de la Comisión Interamericana de Derechos Humanos sobre la condición de las personas privadas de libertad en Honduras,ultimar y aplicar en consonancia la política penitenciaria nacional.',
                'details' => '',
                'total' => 0.0,
                'created_at' => '2016-12-15 00:44:22',
                'updated_at' => '2016-12-15 00:44:22',
            ),
            37 => 
            array (
                'id' => 43,
                'typeofrecomendations_id' => 1,
                'country_id' => 15,
                'name' => 'Velar porque todos los delitos motivados por prejuicios se categoricen como tal y se investiguen en profundidad.',
                'details' => '',
                'total' => 0.0,
                'created_at' => '2016-12-15 00:44:52',
                'updated_at' => '2016-12-15 00:44:52',
            ),
            38 => 
            array (
                'id' => 44,
                'typeofrecomendations_id' => 1,
                'country_id' => 15,
                'name' => 'Velar porque se apruebe y se aplique la Ley de Identidad de Genero que actualmente esta siendo examinada en el congreso.',
                'details' => '',
                'total' => 0.0,
                'created_at' => '2016-12-15 00:46:31',
                'updated_at' => '2016-12-15 00:46:31',
            ),
            39 => 
            array (
                'id' => 45,
                'typeofrecomendations_id' => 1,
                'country_id' => 16,
                'name' => 'Continuar con esfuerzos debidos para la debida proteccion a mujeres que forman parte del programa de proteccion a vistimas y testigos',
                'details' => '',
                'total' => 0.0,
                'created_at' => '2016-12-15 00:47:00',
                'updated_at' => '2016-12-15 00:47:00',
            ),
            40 => 
            array (
                'id' => 46,
                'typeofrecomendations_id' => 1,
                'country_id' => 16,
                'name' => 'Fortalecer las acciones encaminadas a implementar políticas de inclusión social y desarrollo que reduzcan los niveles de desigualdad y pobreza.',
                'details' => '',
                'total' => 0.0,
                'created_at' => '2016-12-15 00:49:05',
                'updated_at' => '2016-12-15 00:49:05',
            ),
            41 => 
            array (
                'id' => 47,
                'typeofrecomendations_id' => 1,
                'country_id' => 17,
                'name' => 'Llevar a cabo programas y campañas de sencibilizacion para promover la tolerancia y combatir la violencia de que son victimas las personas lesbianas, gais, transgenero,bisexuales e intersexuales.',
                'details' => '',
                'total' => 0.0,
                'created_at' => '2016-12-15 00:49:36',
                'updated_at' => '2016-12-15 00:49:36',
            ),
            42 => 
            array (
                'id' => 48,
                'typeofrecomendations_id' => 1,
                'country_id' => 17,
                'name' => 'Adoptar todas las medidas necesarias para asegurar la aplicación efectiva del código penal,que castiga el delito de feminicidio.',
                'details' => '',
                'total' => 0.0,
                'created_at' => '2016-12-15 00:49:56',
                'updated_at' => '2016-12-15 00:49:56',
            ),
            43 => 
            array (
                'id' => 49,
                'typeofrecomendations_id' => 1,
                'country_id' => 17,
                'name' => 'Asegurar una rapida investigacion de los ataques y amenazas sufridos por los defensores de los derechos humanos, los pueblos indígenas y los periodistas y velar porque estos puedan llevar a cabo su función sin miedo a replesalias.',
                'details' => '',
                'total' => 0.0,
                'created_at' => '2016-12-15 00:50:29',
                'updated_at' => '2016-12-15 00:50:29',
            ),
            44 => 
            array (
                'id' => 50,
                'typeofrecomendations_id' => 1,
                'country_id' => 17,
            'name' => 'Ratificar el protocolo facultativo de la convención sobre la eliminación de todas las formas de discriminación contra la mujer (OP-CEDAW)',
                'details' => '',
                'total' => 0.0,
                'created_at' => '2016-12-15 00:51:43',
                'updated_at' => '2016-12-15 00:51:43',
            ),
            45 => 
            array (
                'id' => 51,
                'typeofrecomendations_id' => 1,
                'country_id' => 18,
                'name' => 'Implementar de manera efectiva el plan de Igualdad y Equidad de genero 2010-2022,mediante la asignación de recursos técnicos y financieros para alcanzar los objetivos previstos así como la re-apertura de la linea ¨114¨ de emergencia para brindar atención',
                'details' => '',
                'total' => 0.0,
                'created_at' => '2016-12-15 00:52:23',
                'updated_at' => '2016-12-15 00:52:23',
            ),
            46 => 
            array (
                'id' => 52,
                'typeofrecomendations_id' => 1,
                'country_id' => 18,
                'name' => 'Investigar de manera exhaustiva los homicidios de mujeres por razones genero.',
                'details' => '',
                'total' => 0.0,
                'created_at' => '2016-12-15 00:52:48',
                'updated_at' => '2016-12-15 00:52:48',
            ),
            47 => 
            array (
                'id' => 53,
                'typeofrecomendations_id' => 1,
                'country_id' => 18,
                'name' => 'Adaptar plenamente su legislacion al Estatuto de Roma de la Corte Penal Internacional',
                'details' => '',
                'total' => 0.0,
                'created_at' => '2016-12-15 00:53:12',
                'updated_at' => '2016-12-15 00:53:12',
            ),
            48 => 
            array (
                'id' => 54,
                'typeofrecomendations_id' => 1,
                'country_id' => 18,
                'name' => 'Continuar las acciones para que la protección de los defensores de los derechos humanos,periodistas, comunicadores sociales y funcionarios del sector de la justicia sea plena y efectiva, de manera que estos pueden realizar su trabajo con todas las garantías.',
                'details' => '',
                'total' => 0.0,
                'created_at' => '2016-12-15 00:53:29',
                'updated_at' => '2016-12-15 00:53:29',
            ),
            49 => 
            array (
                'id' => 55,
                'typeofrecomendations_id' => 1,
                'country_id' => 18,
            'name' => 'Ratificar el (OP-CEDAW) como se había recomendado anteriormente.',
                'details' => '',
                'total' => 0.0,
                'created_at' => '2016-12-15 00:56:00',
                'updated_at' => '2016-12-15 00:56:00',
            ),
            50 => 
            array (
                'id' => 56,
                'typeofrecomendations_id' => 1,
                'country_id' => 19,
                'name' => 'Mejorar la precaria situación de los pueblos indígenas y las comunidades afrodescendientes.',
                'details' => '',
                'total' => 0.0,
                'created_at' => '2016-12-15 00:56:22',
                'updated_at' => '2016-12-15 00:56:22',
            ),
            51 => 
            array (
                'id' => 57,
                'typeofrecomendations_id' => 1,
                'country_id' => 19,
                'name' => 'Adecuar plenamente de su derecho interno al estatuto de Roma de la Corte Penal Internacional.',
                'details' => '',
                'total' => 0.0,
                'created_at' => '2016-12-15 00:58:19',
                'updated_at' => '2016-12-15 00:58:19',
            ),
            52 => 
            array (
                'id' => 58,
                'typeofrecomendations_id' => 1,
                'country_id' => 19,
                'name' => 'Adoptar medidas firmes de lucha contra la impunidad penal.',
                'details' => '',
                'total' => 0.0,
                'created_at' => '2016-12-15 00:59:37',
                'updated_at' => '2016-12-15 00:59:37',
            ),
            53 => 
            array (
                'id' => 59,
                'typeofrecomendations_id' => 1,
                'country_id' => 19,
                'name' => 'Respetar y proteger el derecho a la libertad de expresión y reforzar la protección de los periodistas,activistas de sociedad civil y defensores de los derechos humanos contra posibles ataques.',
                'details' => '',
                'total' => 0.0,
                'created_at' => '2016-12-15 00:59:58',
                'updated_at' => '2016-12-15 00:59:58',
            ),
            54 => 
            array (
                'id' => 60,
                'typeofrecomendations_id' => 1,
                'country_id' => 20,
                'name' => 'Reforzar el poder judicial aplicando un proceso de selección transparente,basado en el merito y claramente definido para los jueces de la corte suprema',
                'details' => '',
                'total' => 0.0,
                'created_at' => '2016-12-15 01:00:42',
                'updated_at' => '2016-12-15 01:00:42',
            ),
            55 => 
            array (
                'id' => 61,
                'typeofrecomendations_id' => 1,
                'country_id' => 20,
                'name' => 'Seguir reforzando la capacidad gubernamental para investigar y perseguir eficazmente todos los delitos,incluidas las contravenciones del derecho laboral',
                'details' => '',
                'total' => 0.0,
                'created_at' => '2016-12-15 01:02:02',
                'updated_at' => '2016-12-15 01:02:02',
            ),
            56 => 
            array (
                'id' => 62,
                'typeofrecomendations_id' => 1,
                'country_id' => 20,
                'name' => ' Mantener su compromiso de introducir un plan integral de reforma policial y aprobar la nueva Ley orgánica de la policía Nacional de aquí a junio de 2015,y compartir un plan con plazos concretos y cotas de referencia para que los militares dejen de desempeñar labores de la policía civil.',
                'details' => '',
                'total' => 0.0,
                'created_at' => '2016-12-15 01:02:34',
                'updated_at' => '2016-12-15 01:02:34',
            ),
            57 => 
            array (
                'id' => 63,
                'typeofrecomendations_id' => 1,
                'country_id' => 21,
                'name' => 'Asignar recursos suficientes para la aplicación de su plan nacional de acción en derechos humanos.',
                'details' => '',
                'total' => 0.0,
                'created_at' => '2016-12-15 01:03:11',
                'updated_at' => '2016-12-15 01:03:11',
            ),
            58 => 
            array (
                'id' => 64,
                'typeofrecomendations_id' => 1,
                'country_id' => 21,
                'name' => 'Estudiar la posibilidad de celebrar acuerdos bilaterales o multilaterales de cooperación con los Estados pertinentes para atender las necesidades de protección de los niños migrantes no acompañados de Honduras, entre otras cosas en materia de repatriación y reintegración.',
                'details' => '',
                'total' => 0.0,
                'created_at' => '2016-12-15 01:03:45',
                'updated_at' => '2016-12-15 01:03:45',
            ),
            59 => 
            array (
                'id' => 65,
                'typeofrecomendations_id' => 1,
                'country_id' => 21,
            'name' => 'Ratificar el convenio Num,189 de la OIT (Magadagascar);intensificar los esfuerzos destinados a ratificar otras convenciones y convenios internacionales de derechos humanos como el convenio Num. 189 de la OIT.',
                'details' => '',
                'total' => 0.0,
                'created_at' => '2016-12-15 01:04:23',
                'updated_at' => '2016-12-15 01:04:23',
            ),
            60 => 
            array (
                'id' => 66,
                'typeofrecomendations_id' => 1,
                'country_id' => 22,
                'name' => 'Aprobar nuevas medidas concretas para aplicar plan nacional de acción en derechos humanos en 2013, para mantener el descenso de las tasas de delincuencia en el contexto del refuerzo del estado de derecho.',
                'details' => '',
                'total' => 0.0,
                'created_at' => '2016-12-15 01:04:47',
                'updated_at' => '2016-12-15 01:04:47',
            ),
            61 => 
            array (
                'id' => 67,
                'typeofrecomendations_id' => 1,
                'country_id' => 22,
                'name' => 'Proseguir la labor legislativa iniciada en 2014 para proteger a los periodistas, los defensores de los derechos humanos y algunos miembros del poder judicial en la lucha contra la delincuencia.',
                'details' => '',
                'total' => 0.0,
                'created_at' => '2016-12-15 01:06:46',
                'updated_at' => '2016-12-15 01:06:46',
            ),
            62 => 
            array (
                'id' => 68,
                'typeofrecomendations_id' => 1,
                'country_id' => 22,
                'name' => 'Proseguir los esfuerzos iniciados para limitar los flujos de migrantes, sobre todo de niños ,y seguir aplicando el marco legislativo para lograr una educación de calidad para los niños.',
                'details' => '',
                'total' => 0.0,
                'created_at' => '2016-12-15 01:07:12',
                'updated_at' => '2016-12-15 01:07:12',
            ),
            63 => 
            array (
                'id' => 69,
                'typeofrecomendations_id' => 1,
                'country_id' => 22,
                'name' => 'Firmar y ratificar el PO-CEDAW,estableciendo un mecanismo de comunicación que permita reforzar los instrumentos de lucha contra la violencia y la discriminación sufridas por las mujeres.',
                'details' => '',
                'total' => 0.0,
                'created_at' => '2016-12-15 01:07:35',
                'updated_at' => '2016-12-15 01:07:35',
            ),
            64 => 
            array (
                'id' => 70,
                'typeofrecomendations_id' => 1,
                'country_id' => 23,
                'name' => 'Considerar la ampliación de su legislación penal,no solo penalizando los casos de femicidio,sino todos los casos de violencia contra la mujer.	',
                'details' => '',
                'total' => 0.0,
                'created_at' => '2016-12-15 01:07:55',
                'updated_at' => '2016-12-15 01:07:55',
            ),
            65 => 
            array (
                'id' => 71,
                'typeofrecomendations_id' => 1,
                'country_id' => 23,
                'name' => 'Crear tribunales especializados que traten con exclusividad la problemática de la violencia domestica,que representa aristas particulares.',
                'details' => '',
                'total' => 0.0,
                'created_at' => '2016-12-15 01:08:19',
                'updated_at' => '2016-12-15 01:08:19',
            ),
            66 => 
            array (
                'id' => 72,
                'typeofrecomendations_id' => 1,
                'country_id' => 23,
                'name' => 'Reforzar la comisión nacional de derechos humanos en consonancia con los principios de País.',
                'details' => '',
                'total' => 0.0,
                'created_at' => '2016-12-15 01:08:57',
                'updated_at' => '2016-12-15 01:08:57',
            ),
            67 => 
            array (
                'id' => 73,
                'typeofrecomendations_id' => 1,
                'country_id' => 24,
                'name' => 'Reforzar el marco institucional creado en beneficio de los pueblos indígenas y afrohondureños.',
                'details' => '',
                'total' => 0.0,
                'created_at' => '2016-12-15 01:09:28',
                'updated_at' => '2016-12-15 01:09:28',
            ),
            68 => 
            array (
                'id' => 74,
                'typeofrecomendations_id' => 1,
                'country_id' => 24,
                'name' => 'Reforzar el proceso legislativo en curso con respecto al sector educativo.',
                'details' => '',
                'total' => 0.0,
                'created_at' => '2016-12-15 01:09:49',
                'updated_at' => '2016-12-15 01:09:49',
            ),
            69 => 
            array (
                'id' => 75,
                'typeofrecomendations_id' => 1,
                'country_id' => 24,
                'name' => 'Dar seguimiento a las iniciativas emprendidas para reforzar la protección de los derechos del niño.',
                'details' => '',
                'total' => 0.0,
                'created_at' => '2016-12-15 01:10:10',
                'updated_at' => '2016-12-15 01:10:10',
            ),
            70 => 
            array (
                'id' => 76,
                'typeofrecomendations_id' => 1,
                'country_id' => 25,
                'name' => 'Seguir esforzándose por garantizar el esfuerzo de la Comisión Nacional de Derechos Humanos para adecuarla a los principios de País.	',
                'details' => '',
                'total' => 0.0,
                'created_at' => '2016-12-15 01:10:46',
                'updated_at' => '2016-12-15 01:10:46',
            ),
            71 => 
            array (
                'id' => 77,
                'typeofrecomendations_id' => 1,
                'country_id' => 25,
                'name' => 'Seguir aplicando la política de educación publica,gratuita y obligatoria, re-definir la duración y los ciclos y asignar recursos y presupuestos suficiente.	',
                'details' => '',
                'total' => 0.0,
                'created_at' => '2016-12-15 01:11:11',
                'updated_at' => '2016-12-15 01:11:11',
            ),
            72 => 
            array (
                'id' => 78,
                'typeofrecomendations_id' => 1,
                'country_id' => 26,
                'name' => 'Adoptar todas las medidas necesarias para que se sancione de garantizar el acceso efectivo a la justicia de las mujeres victimas de la violencia y su protección de manera efectiva el delito de femicidio tipificado en código penal.',
                'details' => '',
                'total' => 0.0,
                'created_at' => '2016-12-15 01:11:34',
                'updated_at' => '2016-12-15 01:11:34',
            ),
            73 => 
            array (
                'id' => 79,
                'typeofrecomendations_id' => 1,
                'country_id' => 26,
                'name' => ' Garantizar la provisión de recursos humanos y financieros suficientes para la aplicación de la ley de protección de defensores de derechos humanos,periodistas,comunicadores sociales, y operadores de justicia,y comprometerse a examinar su funcionamiento,entre otras cosas su coherencia con las normas internacionales de derechos humanos,tras un periodo de aplicación inicial.',
                'details' => '',
                'total' => 0.0,
                'created_at' => '2016-12-15 01:13:23',
                'updated_at' => '2016-12-15 01:13:23',
            ),
            74 => 
            array (
                'id' => 80,
                'typeofrecomendations_id' => 1,
                'country_id' => 27,
                'name' => 'Asegurar la aplicación efectiva de la ley de protección de defensores de derechos humanos,periodistas,comunicadores sociales y operadores de justicia,y aportar recursos suficientes para establecer un mecanismo eficaz de protección de los defensores de los derechos humanos.',
                'details' => '',
                'total' => 0.0,
                'created_at' => '2016-12-15 01:13:54',
                'updated_at' => '2016-12-15 01:13:54',
            ),
            75 => 
            array (
                'id' => 81,
                'typeofrecomendations_id' => 1,
                'country_id' => 27,
                'name' => ' Garantizar la protección y el acceso efectivo a la justicia de las mujeres victimas de la violencia,entre otras cosas asegurando que los autores de esa violencia comparezcan ante la justicia y proporcionando recursos suficientes y capacitación especifica a las fuerzas del orden,poder judicial y personal sanitario.',
                'details' => '',
                'total' => 0.0,
                'created_at' => '2016-12-15 01:16:05',
                'updated_at' => '2016-12-15 01:16:05',
            ),
            76 => 
            array (
                'id' => 82,
                'typeofrecomendations_id' => 1,
                'country_id' => 27,
                'name' => 'Intensificar los esfuerzos destinados a crear un entorno seguro para los defensores de derechos humanos y los periodistas.',
                'details' => '',
                'total' => 0.0,
                'created_at' => '2016-12-15 01:16:44',
                'updated_at' => '2016-12-15 01:16:44',
            ),
            77 => 
            array (
                'id' => 83,
                'typeofrecomendations_id' => 1,
                'country_id' => 27,
                'name' => 'Reforzar el poder judicial y garantizar su autonomía, independencia e imparcialidad,entre otras cosas adoptando medidas de salvaguardia para impedir las destituciones y los nombramientos irregulares de jueces.',
                'details' => '',
                'total' => 0.0,
                'created_at' => '2016-12-15 01:17:40',
                'updated_at' => '2016-12-15 01:17:40',
            ),
            78 => 
            array (
                'id' => 84,
                'typeofrecomendations_id' => 1,
                'country_id' => 28,
                'name' => 'Mejorar la parte del código penal en que se penalizan los delitos motivados por prejuicios.',
                'details' => '',
                'total' => 0.0,
                'created_at' => '2016-12-15 01:18:36',
                'updated_at' => '2016-12-15 01:18:36',
            ),
            79 => 
            array (
                'id' => 85,
                'typeofrecomendations_id' => 1,
                'country_id' => 28,
                'name' => 'Elaborar leyes contra la discriminación racial.',
                'details' => '',
                'total' => 0.0,
                'created_at' => '2016-12-15 01:19:00',
                'updated_at' => '2016-12-15 01:19:00',
            ),
            80 => 
            array (
                'id' => 86,
                'typeofrecomendations_id' => 1,
                'country_id' => 28,
                'name' => 'Aprobar leyes para proteger la libertad de expresión y la libertad de los medios de comunicación.',
                'details' => '',
                'total' => 0.0,
                'created_at' => '2016-12-15 01:19:24',
                'updated_at' => '2016-12-15 01:19:24',
            ),
            81 => 
            array (
                'id' => 87,
                'typeofrecomendations_id' => 1,
                'country_id' => 28,
                'name' => 'Proseguir la labor de la comisión de la verdad y reconciliación.',
                'details' => '',
                'total' => 0.0,
                'created_at' => '2016-12-15 01:19:57',
                'updated_at' => '2016-12-15 01:19:57',
            ),
            82 => 
            array (
                'id' => 88,
                'typeofrecomendations_id' => 1,
                'country_id' => 29,
            'name' => 'Ratificar el protocolo facultativo del pacto internacional de derechos Económicos, Sociales y Culturales (OP-ICESCR)',
                'details' => '',
                'total' => 0.0,
                'created_at' => '2016-12-15 01:22:45',
                'updated_at' => '2016-12-15 01:22:45',
            ),
            83 => 
            array (
                'id' => 89,
                'typeofrecomendations_id' => 1,
                'country_id' => 29,
                'name' => 'Aprobar una ley de identidad de genero que permita reconocer jurídicamente en el registro nacional a las personas con arreglo a su orientación sexual y la imagen de las personas en cuestión.',
                'details' => '',
                'total' => 0.0,
                'created_at' => '2016-12-15 01:23:08',
                'updated_at' => '2016-12-15 01:23:08',
            ),
            84 => 
            array (
                'id' => 90,
                'typeofrecomendations_id' => 1,
                'country_id' => 30,
                'name' => 'Adoptar medidas institucionales para mejorar la calidad de vida, asegurar la permanencia de los menores y adolescentes en el país y prevenir su migración no acompañada.en los procesos de repatriación, asegurar que se respete el principio del interés superior del niño y se promueva su efectiva reintegración social.',
                'details' => '',
                'total' => 0.0,
                'created_at' => '2016-12-15 01:24:33',
                'updated_at' => '2016-12-15 01:24:33',
            ),
            85 => 
            array (
                'id' => 91,
                'typeofrecomendations_id' => 1,
                'country_id' => 30,
                'name' => 'Diseñar una estrategia integral con perspectiva de genero y derechos humanos para atender a la población que vive en condiciones de pobreza y pobreza extrema.',
                'details' => '',
                'total' => 0.0,
                'created_at' => '2016-12-15 01:25:00',
                'updated_at' => '2016-12-15 01:25:00',
            ),
            86 => 
            array (
                'id' => 92,
                'typeofrecomendations_id' => 1,
                'country_id' => 30,
                'name' => 'Considerar positivamente la ratificacion del OP-CEDAW',
                'details' => '',
                'total' => 0.0,
                'created_at' => '2016-12-15 01:25:23',
                'updated_at' => '2016-12-15 01:25:23',
            ),
            87 => 
            array (
                'id' => 93,
                'typeofrecomendations_id' => 1,
                'country_id' => 31,
                'name' => 'Responder de manera oportuna a todas las comunicaciones de los procedimientos especiales temáticos.',
                'details' => '',
                'total' => 0.0,
                'created_at' => '2016-12-15 01:25:52',
                'updated_at' => '2016-12-15 01:25:52',
            ),
            88 => 
            array (
                'id' => 94,
                'typeofrecomendations_id' => 1,
                'country_id' => 31,
            'name' => 'Ratificar el protocolo facultado del Pacto Internacional de Derechos Económicos,Sociales y Culturales (OP-ICESCR)',
                'details' => '',
                'total' => 0.0,
                'created_at' => '2016-12-15 01:26:17',
                'updated_at' => '2016-12-15 01:26:17',
            ),
            89 => 
            array (
                'id' => 95,
                'typeofrecomendations_id' => 1,
                'country_id' => 32,
                'name' => 'Adoptar medidas para asegurar la plena protección de los niños a todos los niveles y en todas las esferas,y para que las instituciones encargadas de aplicar esas medidas dispongan de fondos y recursos suficientes para desempeñar eficazmente su función.',
                'details' => '',
                'total' => 0.0,
                'created_at' => '2016-12-15 01:28:52',
                'updated_at' => '2016-12-15 01:28:52',
            ),
            90 => 
            array (
                'id' => 96,
                'typeofrecomendations_id' => 1,
                'country_id' => 32,
                'name' => 'Adoptar medidas concretas para aplicar la política publica y plan todas las formas de discriminación de que son victimas los afrohondureños y otros grupos minoritarios.',
                'details' => '',
                'total' => 0.0,
                'created_at' => '2016-12-15 01:29:33',
                'updated_at' => '2016-12-15 01:29:33',
            ),
            91 => 
            array (
                'id' => 97,
                'typeofrecomendations_id' => 1,
                'country_id' => 32,
                'name' => 'Adoptar medidas para reforzar y garantizar la autonomía, independencia e imparcialidad del poder judicial, entre otras cosas procedimientos transparentes e imparciales para el nombramiento y la destitución de los funcionarios judiciales.',
                'details' => '',
                'total' => 0.0,
                'created_at' => '2016-12-15 01:31:14',
                'updated_at' => '2016-12-15 01:31:14',
            ),
            92 => 
            array (
                'id' => 98,
                'typeofrecomendations_id' => 1,
                'country_id' => 33,
                'name' => 'Continuar trabajando en la armonización de su normativa interna con los instrumentos internacionales de derechos humanos en los que el estado es parte.',
                'details' => '',
                'total' => 0.0,
                'created_at' => '2016-12-15 01:31:32',
                'updated_at' => '2016-12-15 01:31:32',
            ),
            93 => 
            array (
                'id' => 99,
                'typeofrecomendations_id' => 1,
                'country_id' => 33,
                'name' => 'Continuar trabajando tanto en el ámbito nacional como en el internacional,en la implementación de la estrategia de seguridad de Centroamérica.',
                'details' => '',
                'total' => 0.0,
                'created_at' => '2016-12-15 01:32:02',
                'updated_at' => '2016-12-15 01:32:02',
            ),
            94 => 
            array (
                'id' => 100,
                'typeofrecomendations_id' => 1,
                'country_id' => 33,
                'name' => 'Adoptar las medidas necesarias para garantizar una justicia imparcial.	',
                'details' => '',
                'total' => 0.0,
                'created_at' => '2016-12-15 01:32:30',
                'updated_at' => '2016-12-15 01:32:30',
            ),
            95 => 
            array (
                'id' => 101,
                'typeofrecomendations_id' => 1,
                'country_id' => 34,
                'name' => 'Seguir promoviendo el disfrute de los derechos y las libertades fundamentales de los ciudadanos en las esferas de educación, la salud, los derechos de las mujeres, los niños y las personas con discapacidad.',
                'details' => '',
                'total' => 0.0,
                'created_at' => '2016-12-15 01:32:51',
                'updated_at' => '2016-12-15 01:32:51',
            ),
            96 => 
            array (
                'id' => 102,
                'typeofrecomendations_id' => 1,
                'country_id' => 35,
                'name' => 'Adoptar mas medidas para investigar, perseguir y castigar de manera efectiva los delitos motivados por prejuicios cometidos contra personas lesbianas, gais, bisexuales,transgenero e intersexuales y contra mujeres, incluidos los femicidios y delitos contra defensores de derechos humanos,periodistas,profesionales de la justicia y miembros de la comunidad campesina del bajo Aguan.',
                'details' => '',
                'total' => 0.0,
                'created_at' => '2016-12-15 01:33:33',
                'updated_at' => '2016-12-15 01:33:33',
            ),
            97 => 
            array (
                'id' => 103,
                'typeofrecomendations_id' => 1,
                'country_id' => 35,
            'name' => 'Elaborar un marco jurídico para los procedimientos disciplinarios (para los jueces).',
                'details' => '',
                'total' => 0.0,
                'created_at' => '2016-12-15 01:34:34',
                'updated_at' => '2016-12-15 01:34:34',
            ),
            98 => 
            array (
                'id' => 104,
                'typeofrecomendations_id' => 1,
                'country_id' => 35,
                'name' => 'Adoptar medidas concretas para aplicar la política publica y plan de nacional de acción en Derechos, Humanos,entre otras cosas asignando fondos suficientes.',
                'details' => '',
                'total' => 0.0,
                'created_at' => '2016-12-15 01:35:03',
                'updated_at' => '2016-12-15 01:35:03',
            ),
            99 => 
            array (
                'id' => 105,
                'typeofrecomendations_id' => 1,
                'country_id' => 35,
                'name' => 'Adoptar medidas eficaces para reforzar y garantizar la independencia y la imparcialidad del poder judicial,entre otras cosas adoptando medidas de salvaguardia para impedir los nombramientos y destituciones irregulares.',
                'details' => '',
                'total' => 0.0,
                'created_at' => '2016-12-15 01:35:28',
                'updated_at' => '2016-12-15 01:35:28',
            ),
            100 => 
            array (
                'id' => 106,
                'typeofrecomendations_id' => 1,
                'country_id' => 1,
                'name' => 'Adecuar el Codigo Penal Al Codigo Internacional de Ética Medica y Considerar la Posibilidad de legalizar el aborto en caso de violación o incesto.',
                'details' => '',
                'total' => 0.0,
                'created_at' => '2016-12-15 01:35:59',
                'updated_at' => '2016-12-15 01:35:59',
            ),
            101 => 
            array (
                'id' => 107,
                'typeofrecomendations_id' => 1,
                'country_id' => 35,
                'name' => ' Atacar las recomendaciones de la comisión Interamericana de Derechos Humanos y la Comisión de la verdad y reconciliación para que las estrategias de seguridad promuevan la prevención y sean aplicadas por cuerpos de policía civil debidamente organizados y capacitados, y no por fuerzas militares.',
                'details' => '',
                'total' => 0.0,
                'created_at' => '2016-12-15 01:37:48',
                'updated_at' => '2016-12-15 01:37:48',
            ),
            102 => 
            array (
                'id' => 108,
                'typeofrecomendations_id' => 1,
                'country_id' => 36,
                'name' => 'Desarrollar un plan nacional de acción para aplicar los principios humanos, incluidas medidas especificas para reforzar la aplicación del convenio Num. 169 de la OIT.',
                'details' => '',
                'total' => 0.0,
                'created_at' => '2016-12-15 01:38:14',
                'updated_at' => '2016-12-15 01:38:14',
            ),
            103 => 
            array (
                'id' => 109,
                'typeofrecomendations_id' => 1,
                'country_id' => 36,
                'name' => 'Aprobar leyes y políticas de protección de los defensores de los derechos humanos y los periodistas,atraer la participación de la sociedad civil en este proceso y aportar los fondos para su aplicación.',
                'details' => '',
                'total' => 0.0,
                'created_at' => '2016-12-15 01:38:34',
                'updated_at' => '2016-12-15 01:38:34',
            ),
            104 => 
            array (
                'id' => 110,
                'typeofrecomendations_id' => 1,
                'country_id' => 37,
                'name' => 'Elaborar directrices para denunciar violaciones de los derechos de las personas privadas de libertad por conducto del mecanismo nacional de prevención de la tortura.',
                'details' => '',
                'total' => 0.0,
                'created_at' => '2016-12-15 01:40:09',
                'updated_at' => '2016-12-15 01:40:09',
            ),
            105 => 
            array (
                'id' => 111,
                'typeofrecomendations_id' => 1,
                'country_id' => 37,
                'name' => 'Intensificar las campañas de sencibilizacion a través del plan nacional de acción contra el racismo y la discriminación racial en proceso de elaboración.',
                'details' => '',
                'total' => 0.0,
                'created_at' => '2016-12-15 01:40:32',
                'updated_at' => '2016-12-15 01:40:32',
            ),
            106 => 
            array (
                'id' => 112,
                'typeofrecomendations_id' => 1,
                'country_id' => 37,
                'name' => 'Redoblar los esfuerzos dirigidos para prevenir con eficacia la violencia contra las mujeres, en particular la violación, la violencia domestica y el acoso sexual.',
                'details' => '',
                'total' => 0.0,
                'created_at' => '2016-12-15 01:40:54',
                'updated_at' => '2016-12-15 01:40:54',
            ),
            107 => 
            array (
                'id' => 113,
                'typeofrecomendations_id' => 1,
                'country_id' => 38,
                'name' => 'Apoyar los esfuerzos del mecanismo nacional de seguimiento de las recomendaciones del Examen Periódico Universal por medio de la creación de un sistema en linea de seguimiento.',
                'details' => '',
                'total' => 0.0,
                'created_at' => '2016-12-15 01:41:33',
                'updated_at' => '2016-12-15 01:41:33',
            ),
            108 => 
            array (
                'id' => 114,
                'typeofrecomendations_id' => 1,
                'country_id' => 38,
                'name' => 'Tomar las medidas necesarias que permitan la reintegración social de niños, niñas y adolescentes victimas de bandas armadas.',
                'details' => '',
                'total' => 0.0,
                'created_at' => '2016-12-15 01:41:55',
                'updated_at' => '2016-12-15 01:41:55',
            ),
            109 => 
            array (
                'id' => 115,
                'typeofrecomendations_id' => 1,
                'country_id' => 38,
                'name' => 'Considerar la posibilidad de aprobar el proyecto de ley de protección a defensores de derechos humanos,periodistas,comunicadores sociales y operadores de justicia.',
                'details' => '',
                'total' => 0.0,
                'created_at' => '2016-12-15 01:42:14',
                'updated_at' => '2016-12-15 01:42:14',
            ),
            110 => 
            array (
                'id' => 116,
                'typeofrecomendations_id' => 1,
                'country_id' => 38,
                'name' => 'Tomar las medidas necesarias para garantizar los derechos humanos de las mujeres y niños migrantes,que incluyen madres solteras y niños no acompañados.',
                'details' => '',
                'total' => 0.0,
                'created_at' => '2016-12-15 01:42:30',
                'updated_at' => '2016-12-15 01:42:30',
            ),
            111 => 
            array (
                'id' => 117,
                'typeofrecomendations_id' => 1,
                'country_id' => 39,
                'name' => 'Prevenir y sancionar todas las formas de violencia contra las mujeres y las niñas y consolidar una mayor representación femenina en los puestos directivos y de adopción de decisiones.',
                'details' => '',
                'total' => 0.0,
                'created_at' => '2016-12-15 01:43:37',
                'updated_at' => '2016-12-15 01:43:37',
            ),
            112 => 
            array (
                'id' => 118,
                'typeofrecomendations_id' => 1,
                'country_id' => 39,
                'name' => 'Proseguir los esfuerzos encaminados a aprobar la ley de protección de defensores de derechos humanos, periodistas, comunicadores sociales y operadores de justicia.',
                'details' => '',
                'total' => 0.0,
                'created_at' => '2016-12-15 01:44:03',
                'updated_at' => '2016-12-15 01:44:03',
            ),
            113 => 
            array (
                'id' => 119,
                'typeofrecomendations_id' => 1,
                'country_id' => 39,
                'name' => 'Continuar con los esfuerzos destinados a potenciar la participación y consulta de los pueblos indígenas sobre las políticas publicas que los afecten, aplicando plenamente la declaración de las Naciones Unidas sobre los derechos de los pueblos indígenas y el convenio Num. 169 de la OIT, sobre pueblos indígenas y tribales en países independientes.',
                'details' => '',
                'total' => 0.0,
                'created_at' => '2016-12-15 01:44:25',
                'updated_at' => '2016-12-15 01:44:25',
            ),
            114 => 
            array (
                'id' => 120,
                'typeofrecomendations_id' => 1,
                'country_id' => 39,
                'name' => 'Considerar la ratificación del OP-ICESCR.',
                'details' => '',
                'total' => 0.0,
                'created_at' => '2016-12-15 01:45:07',
                'updated_at' => '2016-12-15 01:45:07',
            ),
            115 => 
            array (
                'id' => 121,
                'typeofrecomendations_id' => 1,
                'country_id' => 39,
                'name' => 'Considerar la ratificación OP-CEDAW.',
                'details' => '',
                'total' => 0.0,
                'created_at' => '2016-12-15 01:47:19',
                'updated_at' => '2016-12-15 01:47:19',
            ),
            116 => 
            array (
                'id' => 122,
                'typeofrecomendations_id' => 1,
                'country_id' => 40,
                'name' => 'Combatir eficazmente la impunidad de los autores de delitos cometidos contra jueces, periodistas y defensores de derechos humanos, e investigar eficazmente las violaciones de derechos humanos en esos casos.',
                'details' => '',
                'total' => 0.0,
                'created_at' => '2016-12-15 01:48:32',
                'updated_at' => '2016-12-15 01:48:32',
            ),
            117 => 
            array (
                'id' => 123,
                'typeofrecomendations_id' => 1,
                'country_id' => 40,
                'name' => 'Adoptar medidas para percibir adecuadamente a los niños y adolescentes expulsados de otro país.',
                'details' => '',
                'total' => 0.0,
                'created_at' => '2016-12-15 01:48:50',
                'updated_at' => '2016-12-15 01:48:50',
            ),
            118 => 
            array (
                'id' => 124,
                'typeofrecomendations_id' => 1,
                'country_id' => 41,
                'name' => 'Considerar la elaboración en indicadores de derechos humanos, según lo sugerido por el ACNUDH, como instrumento para evaluar de manera mas precisa y coherente las políticas nacionales de Derechos Humanos.',
                'details' => '',
                'total' => 0.0,
                'created_at' => '2016-12-15 01:49:25',
                'updated_at' => '2016-12-15 01:49:25',
            ),
            119 => 
            array (
                'id' => 125,
                'typeofrecomendations_id' => 1,
                'country_id' => 41,
                'name' => 'Adoptar medidas adecuadas necesarias para combatir la violencia contra las mujeres.',
                'details' => '',
                'total' => 0.0,
                'created_at' => '2016-12-15 01:50:24',
                'updated_at' => '2016-12-15 01:50:24',
            ),
            120 => 
            array (
                'id' => 126,
                'typeofrecomendations_id' => 1,
                'country_id' => 41,
                'name' => 'Aplicar plenamente el Estatuto de Roma de la Corte Penal Internacional en la legislación Nacional.',
                'details' => '',
                'total' => 0.0,
                'created_at' => '2016-12-15 01:50:44',
                'updated_at' => '2016-12-15 01:50:44',
            ),
            121 => 
            array (
                'id' => 127,
                'typeofrecomendations_id' => 1,
                'country_id' => 41,
            'name' => 'Ratificar el protocolo facultativo de la convención sobre la eliminación de todas las formas de discriminación contra la mujer (OP-CEDAW)',
                'details' => '',
                'total' => 0.0,
                'created_at' => '2016-12-15 01:51:02',
                'updated_at' => '2016-12-15 01:51:02',
            ),
            122 => 
            array (
                'id' => 128,
                'typeofrecomendations_id' => 1,
                'country_id' => 41,
                'name' => 'Ratificar el OP-CRC-IC.',
                'details' => '',
                'total' => 0.0,
                'created_at' => '2016-12-15 01:51:25',
                'updated_at' => '2016-12-15 01:51:25',
            ),
            123 => 
            array (
                'id' => 129,
                'typeofrecomendations_id' => 1,
                'country_id' => 41,
            'name' => 'Ratificar el protocolo facultativo del pacto internacional de derechos económicos, sociales y culturales (OP-ICESCR).',
                'details' => '',
                'total' => 0.0,
                'created_at' => '2016-12-15 01:51:44',
                'updated_at' => '2016-12-15 01:51:44',
            ),
            124 => 
            array (
                'id' => 130,
                'typeofrecomendations_id' => 1,
                'country_id' => 42,
                'name' => 'Proseguir los esfuerzos de reforma de las leyes sobre los derechos de las mujeres y los niños en la esfera de la justicia.',
                'details' => '',
                'total' => 0.0,
                'created_at' => '2016-12-15 01:52:42',
                'updated_at' => '2016-12-15 01:52:42',
            ),
            125 => 
            array (
                'id' => 131,
                'typeofrecomendations_id' => 1,
                'country_id' => 42,
                'name' => 'Proseguir las reformas en materia de educación.',
                'details' => '',
                'total' => 0.0,
                'created_at' => '2016-12-15 01:52:58',
                'updated_at' => '2016-12-15 01:52:58',
            ),
            126 => 
            array (
                'id' => 132,
                'typeofrecomendations_id' => 1,
                'country_id' => 43,
                'name' => 'Velar porque los órganos de derechos humanos como el Ministerio Publico y el poder judicial cuenten con los recursos financieros y humanos necesarios y con capacitación en materia de derechos humanos para garantizar su independencia e imparcialidad, de manera que puedan desempeñar eficazmente su función.',
                'details' => '',
                'total' => 0.0,
                'created_at' => '2016-12-15 01:53:34',
                'updated_at' => '2016-12-15 01:53:34',
            ),
            127 => 
            array (
                'id' => 133,
                'typeofrecomendations_id' => 1,
                'country_id' => 43,
                'name' => 'Emendar la legislación para que la difamación, las injurias y las calumnias dejen de estar reguladas en el derecho penal y se regulen con arreglo a normas de derecho civil establecidas en el marco de las recomendaciones y observaciones de las naciones unidas y la CIDH',
                'details' => '',
                'total' => 0.0,
                'created_at' => '2016-12-15 01:58:22',
                'updated_at' => '2016-12-15 01:58:22',
            ),
            128 => 
            array (
                'id' => 134,
                'typeofrecomendations_id' => 1,
                'country_id' => 44,
                'name' => 'Cooperar estrechamente con la oficina de la ACNUDH que se abrirá próximamente en el país en la aplicación de las recomendaciones del Examen Periódico Universal.',
                'details' => '',
                'total' => 0.0,
                'created_at' => '2016-12-15 02:00:11',
                'updated_at' => '2016-12-15 02:00:11',
            ),
            129 => 
            array (
                'id' => 135,
                'typeofrecomendations_id' => 1,
                'country_id' => 44,
                'name' => 'Adoptar medidas adecuadas para mejorar las condiciones de vida y combatir el hacinamiento en las prisiones y otros centros de detención, y para reducir la violencia contra los reclusos y entre ellos.',
                'details' => '',
                'total' => 0.0,
                'created_at' => '2016-12-15 02:00:34',
                'updated_at' => '2016-12-15 02:00:34',
            ),
            130 => 
            array (
                'id' => 136,
                'typeofrecomendations_id' => 1,
                'country_id' => 44,
                'name' => 'Aumentar la eficacia de la prevención, la investigación y el enjuiciamiento de todas las formas de agresión contra los defensores de derechos humanos, los periodistas,los abogados y los jueces,a fin de reducir su incidencia, y combatir la impunidad en esos casos.',
                'details' => '',
                'total' => 0.0,
                'created_at' => '2016-12-15 02:05:27',
                'updated_at' => '2016-12-15 02:05:27',
            ),
            131 => 
            array (
                'id' => 137,
                'typeofrecomendations_id' => 1,
                'country_id' => 44,
                'name' => 'Velar por la aprobación y aplicación de una ley solida de protección a los defensores de derechos humanos, periodistas, comunicadores sociales y operadores de justicia, y por una evaluación periódica del impacto de la ley.',
                'details' => '',
                'total' => 0.0,
                'created_at' => '2016-12-15 02:05:49',
                'updated_at' => '2016-12-15 02:05:49',
            ),
            132 => 
            array (
                'id' => 138,
                'typeofrecomendations_id' => 1,
                'country_id' => 44,
                'name' => 'Mejorar la capacidad y eficacia de las investigaciones y el enjuiciamiento de todas las denuncias de tortura y malos tratos a manos tanto de las fuerzas de seguridad del estado como compañías privadas, y fortalecer salvaguardias jurídicas que disponen las victimas de tortura y malos tratos.',
                'details' => '',
                'total' => 0.0,
                'created_at' => '2016-12-15 02:06:15',
                'updated_at' => '2016-12-15 02:06:15',
            ),
            133 => 
            array (
                'id' => 139,
                'typeofrecomendations_id' => 1,
                'country_id' => 44,
                'name' => 'Reforzar la independencia y transparencia del poder judicial y redoblar los esfuerzos en la lucha contra la impunidad, entre otras cosas basadas en el merito la elección y el nombramiento de los jueces y evitando las injerencias políticas y de otro tipo de labor de estos, incluida su destitución arbitraria.',
                'details' => '',
                'total' => 0.0,
                'created_at' => '2016-12-15 02:06:56',
                'updated_at' => '2016-12-15 02:06:56',
            ),
            134 => 
            array (
                'id' => 140,
                'typeofrecomendations_id' => 1,
                'country_id' => 44,
                'name' => 'Teniendo en cuenta los altos niveles de violencia que siguen existiendo en el país, intensificar los esfuerzos de la lucha contra la delincuencia y la impunidad,con miras a asegurar el derecho a la vida, a la libertad y a la seguridad del ciudadano.',
                'details' => '',
                'total' => 0.0,
                'created_at' => '2016-12-15 02:28:41',
                'updated_at' => '2016-12-15 02:28:41',
            ),
            135 => 
            array (
                'id' => 141,
                'typeofrecomendations_id' => 1,
                'country_id' => 45,
                'name' => 'Justicia Adoptar medidas para combatir la trata de personas, sobre todo de mujeres y niños.',
                'details' => '',
                'total' => 0.0,
                'created_at' => '2016-12-15 02:29:09',
                'updated_at' => '2016-12-15 02:29:09',
            ),
            136 => 
            array (
                'id' => 142,
                'typeofrecomendations_id' => 1,
                'country_id' => 45,
                'name' => 'Adoptar medidas para garantizar la indecencia del poder judicial.',
                'details' => '',
                'total' => 0.0,
                'created_at' => '2016-12-15 02:29:41',
                'updated_at' => '2016-12-15 02:29:41',
            ),
            137 => 
            array (
                'id' => 143,
                'typeofrecomendations_id' => 1,
                'country_id' => 46,
                'name' => 'Seguir trabajando en la lucha contra la trata de personas y el trafico ilegal de drogas.',
                'details' => '',
                'total' => 0.0,
                'created_at' => '2016-12-15 02:32:01',
                'updated_at' => '2016-12-15 02:32:01',
            ),
            138 => 
            array (
                'id' => 144,
                'typeofrecomendations_id' => 1,
                'country_id' => 46,
                'name' => 'Proseguir la labor de protección de los grupos vulnerables de la población, como las mujeres, los niños y los jóvenes.',
                'details' => '',
                'total' => 0.0,
                'created_at' => '2016-12-15 02:33:21',
                'updated_at' => '2016-12-15 02:33:21',
            ),
            139 => 
            array (
                'id' => 145,
                'typeofrecomendations_id' => 1,
                'country_id' => 47,
                'name' => 'Seguir esforzándose por combatir los asesinatos de mujeres y niñas por razones de genero.',
                'details' => '',
                'total' => 0.0,
                'created_at' => '2016-12-15 02:34:15',
                'updated_at' => '2016-12-15 02:34:24',
            ),
            140 => 
            array (
                'id' => 146,
                'typeofrecomendations_id' => 1,
                'country_id' => 47,
                'name' => 'Proseguir los esfuerzos de reducción de violencia que son victimas los niños y los jóvenes.',
                'details' => '',
                'total' => 0.0,
                'created_at' => '2016-12-15 02:35:46',
                'updated_at' => '2016-12-15 02:35:46',
            ),
            141 => 
            array (
                'id' => 147,
                'typeofrecomendations_id' => 1,
                'country_id' => 47,
                'name' => 'Adoptar medidas eficaces para reducir y controlar la proliferación de armas de fuego.',
                'details' => '',
                'total' => 0.0,
                'created_at' => '2016-12-15 02:36:23',
                'updated_at' => '2016-12-15 02:36:23',
            ),
            142 => 
            array (
                'id' => 148,
                'typeofrecomendations_id' => 1,
                'country_id' => 48,
                'name' => 'Ofrecer una amplia protección a los niños, sobre todo a los menores no acompañados, abordando los problemas que dan lugar a su migración, y a menudo su explotación, otorgándoles medios para poder ser repatriados.',
                'details' => '',
                'total' => 0.0,
                'created_at' => '2016-12-15 02:40:25',
                'updated_at' => '2016-12-15 02:40:25',
            ),
            143 => 
            array (
                'id' => 149,
                'typeofrecomendations_id' => 1,
                'country_id' => 48,
                'name' => 'Reforzar las instituciones publicas encargadas de investigar los delitos y la ejecución de justicia penal, especialmente en la esfera de la delincuencia organizada relacionada con delitos de narcotráfico y trata de seres humanos, para crear un clima social',
                'details' => '',
                'total' => 0.0,
                'created_at' => '2016-12-15 02:42:02',
                'updated_at' => '2016-12-15 02:42:02',
            ),
            144 => 
            array (
                'id' => 150,
                'typeofrecomendations_id' => 1,
                'country_id' => 48,
                'name' => 'Crear y seguir aplicando políticas sociales centradas en ofrecer una mejor educación,aumentar la matriculación de alumnos y reducir el abandono escolar.',
                'details' => '',
                'total' => 0.0,
                'created_at' => '2016-12-15 02:42:54',
                'updated_at' => '2016-12-15 02:42:54',
            ),
            145 => 
            array (
                'id' => 151,
                'typeofrecomendations_id' => 1,
                'country_id' => 48,
                'name' => 'Hacer todos los esfuerzos posibles para respetar la dignidad del ser humano, especialmente de las mujeres y los niños, que son mas vulnerables a violaciones manifestas de sus derechos.',
                'details' => '',
                'total' => 0.0,
                'created_at' => '2016-12-15 02:43:26',
                'updated_at' => '2016-12-15 02:43:26',
            ),
            146 => 
            array (
                'id' => 152,
                'typeofrecomendations_id' => 1,
                'country_id' => 48,
                'name' => 'Presentar los informes pendientes a los órganos de tratados pertinentes de las Naciones Unidas.',
                'details' => '',
                'total' => 0.0,
                'created_at' => '2016-12-15 02:44:04',
                'updated_at' => '2016-12-15 02:44:04',
            ),
            147 => 
            array (
                'id' => 153,
                'typeofrecomendations_id' => 1,
                'country_id' => 49,
                'name' => 'Seguir promoviendo la participación de los afrohondureños y las comunidades indígenas en la esfera publica.',
                'details' => '',
                'total' => 0.0,
                'created_at' => '2016-12-15 02:44:25',
                'updated_at' => '2016-12-15 02:44:25',
            ),
            148 => 
            array (
                'id' => 154,
                'typeofrecomendations_id' => 1,
                'country_id' => 49,
                'name' => 'Reforzar las medidas y los criterios normativos destinados a eliminar la violencia domestica de que son objeto las mujeres.',
                'details' => '',
                'total' => 0.0,
                'created_at' => '2016-12-15 02:44:52',
                'updated_at' => '2016-12-15 02:44:52',
            ),
            149 => 
            array (
                'id' => 155,
                'typeofrecomendations_id' => 1,
                'country_id' => 49,
                'name' => 'Acelerar la promulgación y aplicación del proyecto de ley de defensores de derechos humanos,periodistas,comunicadores sociales,y operadores de justicia, y facilitar recursos suficientes para establecer un mecanismo eficaz de protección.',
                'details' => '',
                'total' => 0.0,
                'created_at' => '2016-12-15 02:45:17',
                'updated_at' => '2016-12-15 02:45:17',
            ),
            150 => 
            array (
                'id' => 156,
                'typeofrecomendations_id' => 1,
                'country_id' => 50,
                'name' => 'Seguir reforzando las medidas legislativas y de política para combatir la violencia contra las mujeres.',
                'details' => '',
                'total' => 0.0,
                'created_at' => '2016-12-15 02:46:36',
                'updated_at' => '2016-12-15 02:46:36',
            ),
            151 => 
            array (
                'id' => 157,
                'typeofrecomendations_id' => 1,
                'country_id' => 50,
                'name' => 'Seguir adoptando medidas para combatir la delincuencia organizada, en particular el trafico de drogas, con miras a fomentar un entorno propicio para el disfrute de los derechos humanos de todas las personas.',
                'details' => '',
                'total' => 0.0,
                'created_at' => '2016-12-15 02:47:03',
                'updated_at' => '2016-12-15 02:47:03',
            ),
            152 => 
            array (
                'id' => 158,
                'typeofrecomendations_id' => 1,
                'country_id' => 50,
            'name' => 'Seguir dando prioridad a los esfuerzos destinados a mejorar la salud de la población,entre otras cosas aprobando la provisión de servicios de agua y saneamiento. (Salud)',
                'details' => '',
                'total' => 0.0,
                'created_at' => '2016-12-15 02:47:57',
                'updated_at' => '2016-12-15 02:48:32',
            ),
            153 => 
            array (
                'id' => 159,
                'typeofrecomendations_id' => 1,
                'country_id' => 51,
                'name' => 'Responder eficazmente a todas las formas de violencia contra la mujer, entre otras cosas impartiendo capacitación sobre cuestiones de genero a las fuerzas del orden.',
                'details' => '',
                'total' => 0.0,
                'created_at' => '2016-12-15 02:49:11',
                'updated_at' => '2016-12-15 02:49:11',
            ),
            154 => 
            array (
                'id' => 160,
                'typeofrecomendations_id' => 1,
                'country_id' => 51,
                'name' => 'Realizar un examen y una reforma estructural exhaustivos de la administración de justicia para asegurar la independencia judicial y reducir el numero, cada vez mayor, de casos de impunidad.',
                'details' => '',
                'total' => 0.0,
                'created_at' => '2016-12-15 02:49:34',
                'updated_at' => '2016-12-15 02:49:34',
            ),
            155 => 
            array (
                'id' => 161,
                'typeofrecomendations_id' => 1,
                'country_id' => 51,
                'name' => 'Formular y aplicar una política de control y reducción de armamentos.',
                'details' => '',
                'total' => 0.0,
                'created_at' => '2016-12-15 02:49:58',
                'updated_at' => '2016-12-15 02:49:58',
            ),
            156 => 
            array (
                'id' => 162,
                'typeofrecomendations_id' => 1,
                'country_id' => 51,
                'name' => 'Garantizar que todos los defensores de derechos humanos en Honduras puedan llevar a cabo sus actividades legitimas de derechos humanos de conformidad con la declaración sobre los defensores de derechos humanos.',
                'details' => '',
                'total' => 0.0,
                'created_at' => '2016-12-15 02:50:19',
                'updated_at' => '2016-12-15 02:50:19',
            ),
            157 => 
            array (
                'id' => 163,
                'typeofrecomendations_id' => 1,
                'country_id' => 51,
            'name' => 'Ratificar el protocolo facultativo de la convención sobre la eliminación de todas las formas de discriminación contra la mujer (OP-CEDAW)	',
                'details' => '',
                'total' => 0.0,
                'created_at' => '2016-12-15 02:50:41',
                'updated_at' => '2016-12-15 02:50:41',
            ),
            158 => 
            array (
                'id' => 164,
                'typeofrecomendations_id' => 1,
                'country_id' => 52,
                'name' => 'Asegurar la transparencia y la imparcialidad en el proceso de nombramiento de los jueces, aplicando procedimientos claros y criterios objetivos, y que el personal judicial no este sujeto a injerencias políticas.',
                'details' => '',
                'total' => 0.0,
                'created_at' => '2016-12-15 02:51:00',
                'updated_at' => '2016-12-15 02:51:00',
            ),
        ));
        
        
    }
}
